config/routes.rb
Rails.application.routes.draw do
# For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
  get 'home/index'
  get 'persons/profile'
  devise_for :users       # created by device

  root 'home#index'

  get 'persons/profile', as: 'user_root'

  get 'users/update', as: 'update_users'

  resources :users, :collection => { :complete => :put}

  resources :users do
    resources :stickies
  end
  #get 'sticky#index'
  get 'sticky/index'
  get 'stickies' => 'stickies#destroy'
  #get 'persons/block', as: 'block'
  post 'sticky'    => "stickies#create"


end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/sticky.rb
class Sticky < ApplicationRecord
  belongs_to :user
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  has_many :stickies
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  validates :name, presence: true,
                    length: { minimum: 1 }

  def active_for_authentication?
    super && :active 
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

  skip_before_action :verify_authenticity_token

  def after_sign_in_path_for(resource)
      if current_user.active?
        user_root_path  
      else
        sign_out(current_user)
        user_session_path
      end
  end

  def after_sign_out_path_for(resource)
    root_path
  end

  before_action :configure_permitted_parameters, if:  :devise_controller?

  protected

    def configure_permitted_parameters
      devise_parameter_sanitizer.permit(:sign_up, keys: [:name])
      devise_parameter_sanitizer.permit(:sign_up, keys: [:active])
    end

end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/persons_controller.rb
class PersonsController < ApplicationController
  def profile
      @users = User.all
      @stickies = Sticky.all
  end
end

app/controllers/stickies_controller.rb
class StickiesController < ApplicationController
  def create
    @user = current_user
    @sticky = @user.stickies.create(sticky_params)
  end

  def destroy
    Sticky.where(sticky_id: params[:id]).destroy_all
  end

  private
    def sticky_params
      params.require(:sticky).permit(:sticky_id, :text)
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController

  def update
    user = User.find(params[:user_id])
    user.map{|r| 
      if r.active?
        r.update!(active: 'false')  
      else
        r.update!(active: 'true')
      end
      r        
    }
      if current_user.active?
        redirect_to user_root_path  
      else
        sign_out(current_user)
        redirect_to root_path
      end
  end

  def destroy
    @user = User.find(params[:id])
    @user.destroy

      if user_signed_in?
        redirect_to user_root_path
      else
        redirect_to root_path
      end

  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/persons_helper.rb
module PersonsHelper
end

app/helpers/stickies_helper.rb
module StickiesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/home/index.html.erb
<body style="background: linear-gradient(90deg, #EECFBA, #C5DDE8)">
<header>
<nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
	<div class="collapse navbar-collapse" id="navbarsExampleDefault">
		<ul class="navbar-nav mr-auto"></ul>
		<form class="form-inline my-2 my-lg-0">
<% if user_signed_in? %><span style="color:white">Hello, <%= current_user.name %>!&nbsp;&nbsp;
			<% if current_user.active? %><% else %><br/>Your account is locked&nbsp;&nbsp;<% end %></span>
		<ul class="list-group list-group-horizontal-xl">
			<li class="list-group-item"><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li>
			<% if current_user.active? %><li class="list-group-item"><%= link_to 'Persons profile', user_root_path %></li><% end %>
		</ul>
		<% else %>
		<ul class="list-group list-group-horizontal-xl">
			<li class="list-group-item"><%= link_to 'Log in', new_user_session_path %></li>
			<li class="list-group-item"><%= link_to 'Sign up', new_user_registration_path %></li>
		</ul><% end %>
    		</form>
	</div>
</nav>
</header>
<main role="main">
	<div class="jumbotron">
		<div class="container">
			<h1 class="display-3">Homepage</h1>
			<table class="table table-hover">
				<tr><th>
<div>Hello my dear friend!</div><div style="font-weight:normal"> This web application was created as part of a training assignment. You can sign up/log in and go to the "Persons profile" section.</div>
				</th></tr>
			</table>
		</div>
	</div>
</main>
</body> 

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
<%= yield :head %>
    <title>Itransition</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag 'https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/css/bootstrap.min.css' %>
    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/persons/_xxx.js.erb
$(function() {
	stickies = $('.stickies_class').data('stickies');
	Stickies.alert(stickies);
});

app/views/persons/profile.html.erb
<% if user_signed_in? %>
<%= javascript_tag do %>
    window.stickies = <%=raw Sticky.where(["user_id = ?", current_user.id]).limit(1000).to_json %>;
<% end %>
<script src="http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js"></script>
<script src="http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.2/jquery-ui.min.js"></script>
<script src="/packs/js/json2.js"></script>
<script src="/packs/js/profile.js" data-turbolinks-track="reload"></script>
<body style="background: linear-gradient(90deg, #EECFBA, #C5DDE8)">
<script>
if(performance.navigation.type == 2){
    location.reload(true);}
</script>
    <header>
        <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
           <div class="collapse navbar-collapse" id="navbarsExampleDefault">
              <ul class="navbar-nav mr-auto"></ul>
              <% if user_signed_in? %>
                  <span style="color:white">Hello, <%= current_user.name %>!&nbsp;&nbsp;</span><% end %>
                 <%= form_tag( update_users_path, :method => :put) do %>
                  <ul class="list-group list-group-horizontal-xl">
                  <li class="list-group-item"><%= submit_tag "Banned/Unbanned", class: "btn btn-primary"%></li>
                  <li class="list-group-item"><%= link_to 'Home', root_path %></li>
                     <% if user_signed_in? %><li class="list-group-item"><%= link_to 'Log out', destroy_user_session_path, :method => :delete %></li><% end %>
              </ul>
          </div>
      </nav>
    </header>
    <main role="main">
       <div class="jumbotron">
          <div class="container">
             <h1 class="display-3">Persons profile</h1>
             <table class="table table-hover">
                <tr>
                   <th>
                   <input onclick="if($(this).attr('checked')) $(this).closest('table').find(':checkbox').attr('checked', true); else $(this).closest('table').find(':checkbox').attr('checked', false);" id="select_all" type="checkbox">
                   &nbsp;select all
                   </th>
                   <th>id</th>
                   <th>name</th>
                   <th>email</th>
                   <th>created at</th>
                   <th>last sign in at</th>
                   <th>active</th>
                   <th>actions</th>
                </tr>
                <% @users.each do |user| %>
                <tr>
                <% if user.id!=34 %>
               <td><%= check_box_tag 'user_id[]', user.id %></td>
               <td><%= user.id %></td>
               <td><%= user.name %></td>
               <td><%= user.email %></td>
               <td><%= user.created_at %></td>
               <td><%= user.last_sign_in_at %></td>
               <td><%= user.active %></td>
               <td><%= link_to 'Destroy', user_path(user),
                  method: :delete,
                  data: { confirm: 'Are you sure?' } %></td>
                </tr>
                <% end %>
                <% end %>
             </table>
          </div>
       </div>
    </main>
</body>
<% end %>
<% else %>
    <head>
        <meta http-equiv="refresh" content="0;URL='https://astreika.herokuapp.com'" />
    </head>
<% end %>